foodgram/foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = 'recipe.views.page_not_found'  # noqa
handler500 = 'recipe.views.server_error'  # noqa


urlpatterns = [
    # админка и авторизация
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    # flatpages
    path('about/', include('django.contrib.flatpages.urls')),
    path(
        'about-project/', views.flatpage,
        {'url': '/about-project/'}, name='about-project'),
    path(
        'about-author/', views.flatpage,
        {'url': '/about-author/'}, name='about-author'),
    path(
        'about-spec/', views.flatpage,
        {'url': '/about-spec/'}, name='about-spec'),
    # подключаем urls приложений
    path('', include('social.urls')),
    path('', include('recipe.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

foodgram/recipe/urls.py
from django.urls import path, include

from recipe import views


urlpatterns = [
    # просмотр рецепта
    path('recipe/<int:recipe_id>/', views.recipe_view, name='recipe'),
    # создание нового рецепта
    path('recipe_new/', views.recipe_new, name='recipe_new'),
    # редактирование рецепта
    path(
        'recipe_edit/<int:recipe_id>/',
        views.recipe_edit,
        name='recipe_edit'
    ),
    # удаление рецепта
    path(
        'recipe_delete/<int:recipe_id>/',
        views.recipe_delete,
        name='recipe_delete'
    ),
    # обработка запроса от js
    path('ingredients/', views.Ingredients.as_view(), name='ingredients'),
    # список покупок
    path('cart_list/', views.cart_list, name='cart_list'),
    # скачать список покупок
    path(
        'cart_list/download/',
        views.cart_list_download,
        name='cart_list_download'
    ),
    # удаление рецепта из списка покупок
    path(
        'cart_list/delete/<int:recipe_id>/',
        views.cart_delete_recipe,
        name='cart_delete_recipe'
    ),
    # добавление в список покупок. запрос от js
    path('purchases/', views.Purchases.as_view(), name='add_to_cart'),
    # удаление из списка покупок
    path(
        'purchases/<int:recipe_id>/',
        views.Purchases.as_view(),
        name='remove_from_cart'
    ),
    # рецепты пользователя
    path('<str:username>/', views.profile, name='profile'),
    # главная страница
    path('', views.index, name='index'),
]

foodgram/users/urls.py
from django.urls import path

from users import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

foodgram/recipe/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    tag_options = {
        'breakfast': ['orange', 'Завтрак'],
        'lunch': ['green', 'Обед'],
        'dinner': ['purple', 'Ужин']
    }

    TAG_CHOICES = [
        ('breakfast', 'Завтрак'),
        ('lunch', 'Обед'),
        ('dinner', 'Ужин'),
    ]
    title = models.CharField(
        max_length=10,
        choices=TAG_CHOICES,
        verbose_name='Название тэга'
    )

    def __str__(self):
        return self.title

    @property
    def color(self):
        return self.tag_options[self.title][0]

    @property
    def name(self):
        return self.tag_options[self.title][1]


class Ingredient(models.Model):

    title = models.CharField(
        max_length=300,
        verbose_name='Название'
    )
    dimension = models.CharField(
        max_length=20,
        verbose_name='Единица измерения')

    def __str__(self):
        return str(self.title)


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор'
    )
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    ingredient = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredient',
        through_fields=('recipe', 'ingredient'),
        related_name='ingredients',
        verbose_name='Ингредиенты'
    )
    cooking_time = models.PositiveSmallIntegerField(
        verbose_name='Время приготовления'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    tag = models.ManyToManyField(
        Tag, related_name='tags',
        verbose_name='Тэги'
    )
    image = models.ImageField(
        upload_to='recipe/',
        default='default/default_img.jpg',
        verbose_name='Изображение'
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-pub_date']

    def get_ingredients(self):
        return '\n'.join(
            self.ingredient.all().values_list('title', flat=True))
    get_ingredients.short_description = 'Ингредиенты'

    def get_tags(self):
        return '\n'.join(
            self.tag.all().values_list('title', flat=True))
    get_tags.short_description = 'Тэги'


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='quantities',
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        verbose_name='Ингредиент'
    )
    quantity = models.FloatField(verbose_name='Количество')

    def __str__(self):
        return str(self.ingredient)


class Cart(models.Model):
    shopper = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='carts',
        verbose_name='Покупатель'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='recipe_carts',
        verbose_name='Список рецептов'
    )

    def __str__(self):
        return self.recipe.title

    class Meta:
        unique_together = ('shopper', 'recipe')

foodgram/recipe/forms.py
from django import forms
from django.forms import ModelForm

from recipe.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'tag', 'cooking_time', 'description', 'image')
        widgets = {
            'tag': forms.CheckboxSelectMultiple(),
        }

foodgram/recipe/views.py
import json

from xhtml2pdf import pisa

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import get_template
from django.views.generic import View

from recipe.forms import RecipeForm
from recipe.models import Cart, Ingredient, Recipe, RecipeIngredient, User
from recipe.service import get_ingredients_from_js, get_tags_from_get
from social.forms import CommentForm


def page_not_found(request, exception):
    """
    Cтраница 404
    """
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    """
    Cтраница 500
    """
    return render(request, 'misc/500.html', status=500)


def index(request):
    """
    Главная страница
    """
    recipes = Recipe.objects.select_related(
        'author').prefetch_related('tag',)
    #  https://otus.ru/nest/post/286/
    tags_qs, tags_from_get = get_tags_from_get(request)
    if tags_qs:
        recipes = Recipe.objects.filter(tag__title__in=tags_qs).distinct()
    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {
        'page': page,
        'paginator': paginator,
        'recipe': recipes,
        'tags': tags_from_get
    })


def profile(request, username):
    """
    Страница пользователя
    """
    profile = get_object_or_404(User, username=username)
    profile_recipes = profile.recipes.all()
    tags_qs, tags_from_get = get_tags_from_get(request)
    if tags_qs:
        profile_recipes = Recipe.objects.filter(
            author=profile, tag__title__in=tags_qs).distinct()
    paginator = Paginator(profile_recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {
        'page': page,
        'paginator': paginator,
        'profile': profile,
        'recipe': profile_recipes,
        'tags': tags_from_get
    })


def recipe_view(request, recipe_id):
    """
    Просмотр рецепта
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    comments = recipe.comments.all()
    form = CommentForm()

    return render(request, 'includes/recipe.html', {
        'recipe': recipe,
        'form': form,
        'comments': comments,
    })


@login_required
def recipe_new(request):
    """
    Создание рецепта
    """
    author = get_object_or_404(User, username=request.user)
    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None
    )
    ingredients = get_ingredients_from_js(request)
    if recipe_form.is_valid():
        recipe = recipe_form.save(commit=False)
        recipe.author = author
        recipe.save()
        for title, quantity in ingredients.items():
            ingredient = get_object_or_404(Ingredient, title=title)
            recipe_ingredient = RecipeIngredient(
                quantity=quantity,
                ingredient=ingredient,
                recipe=recipe
            )
            recipe_ingredient.save()
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_form.html', {'form': recipe_form, })


@login_required
def recipe_edit(request, recipe_id):
    """
    Редактирование рецепта
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user != recipe.author:
        return redirect('recipe', recipe_id=recipe.id)
    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None, instance=recipe)
    ingredients = get_ingredients_from_js(request)
    if recipe_form.is_valid():
        RecipeIngredient.objects.filter(recipe=recipe).delete()
        recipe = recipe_form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        recipe.quantities.all().delete()
        for title, quantity in ingredients.items():
            ingredient = get_object_or_404(Ingredient, title=title)
            recipe_ingredient = RecipeIngredient(
                quantity=quantity,
                ingredient=ingredient,
                recipe=recipe
            )
            recipe_ingredient.save()
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_change_form.html', {
        'form': recipe_form,
        'recipe': recipe,
    })


@login_required
def recipe_delete(request, recipe_id):
    """
    Удаление рецепта.
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


class Ingredients(View):
    """
    Фильтрация ингредиентов по GET запросу от js
    """
    def get(self, request):
        ingredient = request.GET['query']
        ingredients = list(Ingredient.objects.filter(
            title__icontains=ingredient).values('title', 'dimension'))
        return JsonResponse(ingredients, safe=False)


class Purchases(View):
    """
    Добавление рецепта в корзину и удаление из неё
    """
    def post(self, request):
        recipe_id = json.loads(request.body)['id']
        recipe = get_object_or_404(Recipe, id=recipe_id)
        Cart.objects.get_or_create(
            shopper=request.user, recipe=recipe)
        return JsonResponse({'success': True})

    def delete(self, request, recipe_id):
        recipe = get_object_or_404(Recipe, id=recipe_id)
        user = get_object_or_404(User, username=request.user.username)
        obj = get_object_or_404(Cart, shopper=user, recipe=recipe)
        obj.delete()
        return JsonResponse({'success': True})


@login_required
def cart_list(request):
    """
    Список рецептов в корзине
    """
    recipes = request.user.carts.all()
    return render(request, 'cart_list.html', {'recipes': recipes})


@login_required
def cart_delete_recipe(request, recipe_id):
    """
    Удаление рецепта из корзины
    """
    recipe = get_object_or_404(Cart, shopper=request.user, recipe=recipe_id)
    recipe.delete()
    return redirect('cart_list')


@login_required
def cart_list_download(request):
    """
    Формирование и скачивание списка ингредиентов в PDF
    """
    recipes = Recipe.objects.filter(recipe_carts__shopper=request.user).values(
        'ingredient__title', 'ingredient__dimension',)
    ingredients = recipes.annotate(Sum('quantities__quantity')).order_by()
    template_path = 'cart_to_pdf.html'
    context = {'ingredients': ingredients}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="shop_list.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(html, dest=response, encoding='UTF-8')
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

foodgram/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}FOODGRAM{% endblock %} | GremTech</title>
    {% load static %}
    {% csrf_token %}
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="/static/pages/index.css">
</head>
<body class="body">
    {% block head %}
    {% endblock %}
    <main class="main container">
        {% block content %}
        {% endblock %}
      </main> 
    {% include 'includes/footer.html' %}
    {% block scripts %}
    {% endblock %}
</body>
</html>

foodgram/templates/cart_list.html
{% extends 'base.html' %}
{% block title %} Список покупок {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with cart_list=True recipe=recipe%}
{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
<div class="main__header">
<h1 class="main__title">Список покупок</h1>
</div>
    <div class="card-list card-list_column">
      <ul class="shopping-list">
        {% for recipe in recipes %}
          <li class="shopping-list__item" data-id="{{ recipe.recipe.id }}">
            <div class="recipe recipe_reverse">
              <img src="{{ recipe.recipe.image.url }}" alt="{{ recipe.recipe.title }}" class="recipe__image recipe__image_big">
              <h3 class="recipe__title"><a style="color: #000" href="{% url 'recipe' recipe.recipe.id %}">{{ recipe.recipe.title }}</a></h3>
              <p class="recipe__text"><span class="icon-time"></span> {{ recipe.recipe.cooking_time }} мин.</p>
            </div>
            <a href="{% url 'cart_delete_recipe' recipe.recipe.id %}" class="shopping-list__button link">Удалить</a>
          </li>
        {% endfor %}
      </ul>
      {% if recipes %}
        <a class="button button_style_blue" href="{% url 'cart_list_download' %}">Скачать список</a>
      {% endif %}
    </div>
{% endblock %}

foodgram/templates/cart_to_pdf.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <title>GremTech</title>
    <style type="text/css">
        @font-face { font-family: arial; src: url('./static/fonts/arial.ttf'); }
        div { font-family: arial; color: #333333; }
    </style>
</head>
<body>
    
    <main>
        <div>
            <h3 align="center">Foodgram - лучшие рецепты!</h3>
            <hr align="center" width="600" size="1" color="#000" />
        </div>
        <p></p>
        <div>
            <h1 align="center">Список покупок</h1>
        </div>
        <hr align="center" width="500" size="1" color="#f00" />
        <div>
            <ul>
            {% for ingredient in ingredients %}
                <li>
                <div>
                    <h2>{{ ingredient.ingredient__title }} - {{ ingredient.quantities__quantity__sum }} {{ ingredient.ingredient__dimension }}</h2>
                </div>
                </li>
            {% endfor %}
            </ul>
            <hr align="center" width="500" size="2" color="#ff0000" />
            <h2 align="center">Спасибо, что воспользовались нашим сервисом!</h2>
        </div>
    </main> 

</body>
</html>

foodgram/templates/favorit.html
{% extends 'base.html' %}
{% block title %} Избранные рецепты {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with favorit=True %}
{% endblock %}
{% block content %}
    {% csrf_token %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}"> 
    <div class="main__header">
        <h1 class="main__title">Избранное</h1>
        {% include 'includes/tags.html' %}
    </div>
    <div class="card-list">
        {% for recipe in page %}
            {% include 'includes/recipe_small.html' with recipe=recipe %}
        {% endfor %}
    </div>
        {% if page.has_other_pages %}
            {% include 'includes/paginator.html' with items=page paginator=paginator %}
        {% endif %}
    {% block script %}
        <script src="{% static 'js/components/MainCards.js' %}"></script>
        <script src="{% static 'js/components/Purchases.js' %}"></script>
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'js/config/config.js' %}"></script>
        <script src="{% static 'js/components/CardList.js' %}"></script>
        <script src="{% static 'js/components/Header.js' %}"></script>
        
        <script src="{% static 'js/api/Api.js' %}"></script>
        <script src="{% static 'js/favorite.js' %}"></script>
    {% endblock %}
{% endblock %}

foodgram/templates/follow.html
{% extends "base.html" %} 
{% block title %} Мои подписки {% endblock %}
{% block head %}
    {% include 'includes/head.html' with follow=True%}
{% endblock head %}
{% load static %}
{% block content %}
{% csrf_token %}
<link rel="stylesheet" href="/static/pages/myFollow.css">
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
        {% include 'includes/follow_card.html'%}
    </div>
    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator %}
    </ul>
    {% endif %}
        
    {% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/myFollow.js' %}"></script>

    {% endblock %}
{% endblock %}

foodgram/templates/index.html
{% extends "base.html" %} 
{% block title %} Foodgram - лучшие рецепты {% endblock title %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with index=True%}
{% endblock head %}
{% block content %}
{% csrf_token %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
        <div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include 'includes/tags.html' %}
        </div>    
        <div class="card-list">
                {% for recipe in page %}
                   {% include 'includes/recipe_small.html' with recipe=recipe %}
                {% endfor %}
       </div>
    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator %}
    </ul>
    {% endif %}

    {% block scripts %}
            <script src="{% static 'js/config/config.js' %}"></script>
            <script src="{% static 'js/components/MainCards.js' %}"></script>
            <script src="{% static 'js/components/Purchases.js' %}"></script>
            <script src="{% static 'js/components/CardList.js' %}"></script>
            <script src="{% static 'js/components/Header.js' %}"></script>
            <script src="{% static 'js/api/Api.js' %}"></script>
        {% if user.is_authenticated %}
            <script src="{% static 'js/components/Favorites.js' %}"></script>
            <script src="{% static 'js/indexAuth.js' %}"></script>
        {% else %}
            <script src="{% static 'js/indexNotAuth.js' %}"></script>
        {% endif %}
    {% endblock scripts %}
{% endblock %}

foodgram/templates/profile.html
{% extends "base.html" %} 
{% block title %} Автор рецептов: {{ profile.get_full_name }} {% endblock %}
{% block head %}
    {% include 'includes/head.html'%}
{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}

<link rel="stylesheet" href="{% static 'pages/index.css' %}">
        <div class="main__header">
            <h1 class="main__title">{{ profile.get_full_name }}</h1>
            {% include 'includes/tags.html' %}
        </div>
        {% csrf_token %}
        {% if user != profile and user.is_authenticated %}
            {% if profile|in_follow:user %}
                <div class="author-subscribe" data-author="{{ profile.id }}">
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span>Отписаться от автора </button></p>
                </div>
            {% else %}
                <div class="author-subscribe" data-author="{{ profile.id }}">
                    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></p>
                </div>
            {% endif %}
        {% endif %}
        <div class="card-list">
               {% for recipe in page %}
                    {% include 'includes/recipe_small.html' %}
                {% endfor %}
        </div>

    {% if page.has_other_pages %}
    <ul class="pagination justify-content-center">
        {% include 'includes/paginator.html' with items=page paginator=paginator %}
    </ul>

    {% endif %}
        
    {% block scripts %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/authorRecipe.js' %}"></script>

    {% endblock scripts %}

{% endblock %}

foodgram/templates/recipe_form.html
{% extends "base.html" %} 
{% block title %} Создание рецепта {% endblock %}
{% load static %}
{% block head %}
    {% include 'includes/head.html' with new_recipe=True%}
{% endblock %}
{% block content %}
{% load user_filters %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    {{ form.title|addclass:"form__input" }}
                    {% if form.errors %}
                    {% for error in form.title.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                    {% for tag_choice, tag_title in form.tag.field.choices %}
                        <div class="tags__item">
                            <input type="checkbox" name="tag" value ="{{ tag_choice.instance.pk }}" id="id_{{ tag_choice.instance.name }}" class="tags__checkbox tags__checkbox_style_{{ tag_choice.instance.color }}">
                            <label for="id_{{ tag_choice.instance.name }}" class="tags__label">{{ tag_choice.instance.name }}</label>
                        </div>
                    {% endfor %}
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                    {% endif %}
               </div>
            </div>
           <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    {{ form.cooking_time|addclass:"form__input" }}
                    <label for="id_time" class="form__label">минут</label>
                    {% if form.errors %}
                    {% for error in field.errors %}
                        <span class="form__error">{{ error|escape }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    {{ form.description|addclass:"form__textarea" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {{ form.image|addclass:"form__file-button" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>
    {% block scripts %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/formRecipe.js' %}"></script>
    {% endblock %}
{% endblock %}

foodgram/templates/tags.html
{% load user_filters %}
<ul class="tags">
  <li class="tags__item">
    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange {% if 'breakfast' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"breakfast" }}"></a>
    <span class="tags__label">Завтрак</span>
  </li>
  <li class="tags__item">
    <a id="lunch" class="tags__checkbox tags__checkbox_style_green {% if 'lunch' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"lunch" }}"></a>
    <span for="lunch" class="tags__label">Обед</span>
  </li>
  <li class="tags__item">
    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple {% if 'dinner' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"dinner" }}"></a>
    <label for="dinner" class="tags__label">Ужин</label>
  </li>
</ul>