foodgram/foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = 'recipe.views.page_not_found'  # noqa
handler500 = 'recipe.views.server_error'  # noqa


urlpatterns = [
    # админка и авторизация
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    # flatpages
    path('about/', include('django.contrib.flatpages.urls')),
    path(
        'about-project/', views.flatpage,
        {'url': '/about-project/'}, name='about-project'),
    path(
        'about-author/', views.flatpage,
        {'url': '/about-author/'}, name='about-author'),
    path(
        'about-spec/', views.flatpage,
        {'url': '/about-spec/'}, name='about-spec'),
    # подключаем urls приложений
    path('', include('social.urls')),
    path('', include('recipe.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

foodgram/recipe/urls.py
from django.urls import path, include

from recipe import views


urlpatterns = [
    # просмотр рецепта
    path('recipe/<int:recipe_id>/', views.recipe_view, name='recipe'),
    # создание нового рецепта
    path('recipe_new/', views.recipe_new, name='recipe_new'),
    # редактирование рецепта
    path(
        'recipe_edit/<int:recipe_id>/',
        views.recipe_edit,
        name='recipe_edit'
    ),
    # удаление рецепта
    path(
        'recipe_delete/<int:recipe_id>/',
        views.recipe_delete,
        name='recipe_delete'
    ),
    # обработка запроса от js
    path('ingredients/', views.Ingredients.as_view(), name='ingredients'),
    # список покупок
    path('cart_list/', views.cart_list, name='cart_list'),
    # скачать список покупок
    path(
        'cart_list/download/',
        views.cart_list_download,
        name='cart_list_download'
    ),
    # удаление рецепта из списка покупок
    path(
        'cart_list/delete/<int:recipe_id>/',
        views.cart_delete_recipe,
        name='cart_delete_recipe'
    ),
    # добавление в список покупок. запрос от js
    path('purchases/', views.Purchases.as_view(), name='add_to_cart'),
    # удаление из списка покупок
    path(
        'purchases/<int:recipe_id>/',
        views.Purchases.as_view(),
        name='remove_from_cart'
    ),
    # рецепты пользователя
    path('<str:username>/', views.profile, name='profile'),
    # главная страница
    path('', views.index, name='index'),
]

foodgram/social/urls.py
from django.urls import path, include

from social import views


app_name = 'social'
urlpatterns = [
    # добавление комментария к рецепту
    path(
        'recipe/<int:recipe_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    # подписки текущего пользователя
    path('follow/', views.follow_index, name='follow_index'),
    # добавление подписки на автора
    path('add_follow/', views.Following.as_view()),
    # удаление подписки
    path('unfollow/<int:author_id>/', views.Following.as_view()),
    # избранное текущего пользователя
    path('favorit/', views.favorit_index, name='favorit_index'),
    # добавление в избранное
    path('add_favorit/', views.Favorites.as_view()),
    # удаление из избранного
    path('unfavorit/<int:recipe_id>/', views.Favorites.as_view()),
]

foodgram/users/urls.py
from django.urls import path

from users import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

foodgram/recipe/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    tag_options = {
        'breakfast': ['orange', 'Завтрак'],
        'lunch': ['green', 'Обед'],
        'dinner': ['purple', 'Ужин']
    }

    TAG_CHOICES = [
        ('breakfast', 'Завтрак'),
        ('lunch', 'Обед'),
        ('dinner', 'Ужин'),
    ]
    title = models.CharField(
        max_length=10,
        choices=TAG_CHOICES,
        verbose_name='Название тэга'
    )

    def __str__(self):
        return self.title

    @property
    def color(self):
        return self.tag_options[self.title][0]

    @property
    def name(self):
        return self.tag_options[self.title][1]


class Ingredient(models.Model):

    title = models.CharField(
        max_length=300,
        verbose_name='Название'
    )
    dimension = models.CharField(
        max_length=20,
        verbose_name='Единица измерения')

    def __str__(self):
        return str(self.title)


class Recipe(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='recipes',
        verbose_name='Автор'
    )
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    ingredient = models.ManyToManyField(
        Ingredient,
        through='RecipeIngredient',
        through_fields=('recipe', 'ingredient'),
        related_name='ingredients',
        verbose_name='Ингредиенты'
    )
    cooking_time = models.PositiveSmallIntegerField(
        verbose_name='Время приготовления'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    tag = models.ManyToManyField(
        Tag, related_name='tags',
        verbose_name='Тэги'
    )
    image = models.ImageField(
        upload_to='recipe/',
        default='default/default_img.jpg',
        verbose_name='Изображение'
    )

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-pub_date']

    def get_ingredients(self):
        return '\n'.join(
            self.ingredient.all().values_list('title', flat=True))
    get_ingredients.short_description = 'Ингредиенты'

    def get_tags(self):
        return '\n'.join(
            self.tag.all().values_list('title', flat=True))
    get_tags.short_description = 'Тэги'


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='quantities',
        verbose_name='Рецепт'
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        verbose_name='Ингредиент'
    )
    quantity = models.FloatField(verbose_name='Количество')

    def __str__(self):
        return str(self.ingredient)


class Cart(models.Model):
    shopper = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='carts',
        verbose_name='Покупатель'
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='recipe_carts',
        verbose_name='Список рецептов'
    )

    def __str__(self):
        return self.recipe.title

    class Meta:
        unique_together = ('shopper', 'recipe')

foodgram/recipe/forms.py
from django import forms
from django.forms import ModelForm

from recipe.models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'tag', 'cooking_time', 'description', 'image')
        widgets = {
            'tag': forms.CheckboxSelectMultiple(),
        }

foodgram/recipe/views.py
import json

from xhtml2pdf import pisa

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import get_template
from django.views.generic import View

from recipe.forms import RecipeForm
from recipe.models import Cart, Ingredient, Recipe, RecipeIngredient, User
from recipe.service import get_ingredients_from_js, get_tags_from_get
from social.forms import CommentForm


def page_not_found(request, exception):
    """
    Cтраница 404
    """
    return render(request, 'misc/404.html', {'path': request.path}, status=404)


def server_error(request):
    """
    Cтраница 500
    """
    return render(request, 'misc/500.html', status=500)


def index(request):
    """
    Главная страница
    """
    recipes = Recipe.objects.select_related(
        'author').prefetch_related('tag',)
    #  https://otus.ru/nest/post/286/
    tags_qs, tags_from_get = get_tags_from_get(request)
    if tags_qs:
        recipes = Recipe.objects.filter(tag__title__in=tags_qs).distinct()
    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {
        'page': page,
        'paginator': paginator,
        'recipe': recipes,
        'tags': tags_from_get
    })


def profile(request, username):
    """
    Страница пользователя
    """
    profile = get_object_or_404(User, username=username)
    profile_recipes = profile.recipes.all()
    tags_qs, tags_from_get = get_tags_from_get(request)
    if tags_qs:
        profile_recipes = Recipe.objects.filter(
            author=profile, tag__title__in=tags_qs).distinct()
    paginator = Paginator(profile_recipes, 6)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {
        'page': page,
        'paginator': paginator,
        'profile': profile,
        'recipe': profile_recipes,
        'tags': tags_from_get
    })


def recipe_view(request, recipe_id):
    """
    Просмотр рецепта
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    comments = recipe.comments.all()
    form = CommentForm()

    return render(request, 'includes/recipe.html', {
        'recipe': recipe,
        'form': form,
        'comments': comments,
    })


@login_required
def recipe_new(request):
    """
    Создание рецепта
    """
    author = get_object_or_404(User, username=request.user)
    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None
    )
    ingredients = get_ingredients_from_js(request)
    if recipe_form.is_valid():
        recipe = recipe_form.save(commit=False)
        recipe.author = author
        recipe.save()
        for title, quantity in ingredients.items():
            ingredient = get_object_or_404(Ingredient, title=title)
            recipe_ingredient = RecipeIngredient(
                quantity=quantity,
                ingredient=ingredient,
                recipe=recipe
            )
            recipe_ingredient.save()
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_form.html', {'form': recipe_form, })


@login_required
def recipe_edit(request, recipe_id):
    """
    Редактирование рецепта
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user != recipe.author:
        return redirect('recipe', recipe_id=recipe.id)
    recipe_form = RecipeForm(
        request.POST or None, files=request.FILES or None, instance=recipe)
    ingredients = get_ingredients_from_js(request)
    if recipe_form.is_valid():
        RecipeIngredient.objects.filter(recipe=recipe).delete()
        recipe = recipe_form.save(commit=False)
        recipe.author = request.user
        recipe.save()
        recipe.quantities.all().delete()
        for title, quantity in ingredients.items():
            ingredient = get_object_or_404(Ingredient, title=title)
            recipe_ingredient = RecipeIngredient(
                quantity=quantity,
                ingredient=ingredient,
                recipe=recipe
            )
            recipe_ingredient.save()
        recipe_form.save_m2m()
        return redirect('index')
    return render(request, 'recipe_change_form.html', {
        'form': recipe_form,
        'recipe': recipe,
    })


@login_required
def recipe_delete(request, recipe_id):
    """
    Удаление рецепта.
    """
    recipe = get_object_or_404(Recipe, id=recipe_id)
    if request.user == recipe.author:
        recipe.delete()
    return redirect('index')


class Ingredients(View):
    """
    Фильтрация ингредиентов по GET запросу от js
    """
    def get(self, request):
        ingredient = request.GET['query']
        ingredients = list(Ingredient.objects.filter(
            title__icontains=ingredient).values('title', 'dimension'))
        return JsonResponse(ingredients, safe=False)


class Purchases(View):
    """
    Добавление рецепта в корзину и удаление из неё
    """
    def post(self, request):
        recipe_id = json.loads(request.body)['id']
        recipe = get_object_or_404(Recipe, id=recipe_id)
        Cart.objects.get_or_create(
            shopper=request.user, recipe=recipe)
        return JsonResponse({'success': True})

    def delete(self, request, recipe_id):
        recipe = get_object_or_404(Recipe, id=recipe_id)
        user = get_object_or_404(User, username=request.user.username)
        obj = get_object_or_404(Cart, shopper=user, recipe=recipe)
        obj.delete()
        return JsonResponse({'success': True})


@login_required
def cart_list(request):
    """
    Список рецептов в корзине
    """
    recipes = request.user.carts.all()
    return render(request, 'cart_list.html', {'recipes': recipes})


@login_required
def cart_delete_recipe(request, recipe_id):
    """
    Удаление рецепта из корзины
    """
    recipe = get_object_or_404(Cart, shopper=request.user, recipe=recipe_id)
    recipe.delete()
    return redirect('cart_list')


@login_required
def cart_list_download(request):
    """
    Формирование и скачивание списка ингредиентов в PDF
    """
    recipes = Recipe.objects.filter(recipe_carts__shopper=request.user).values(
        'ingredient__title', 'ingredient__dimension',)
    ingredients = recipes.annotate(Sum('quantities__quantity')).order_by()
    template_path = 'cart_to_pdf.html'
    context = {'ingredients': ingredients}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="shop_list.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(html, dest=response, encoding='UTF-8')
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

foodgram/templates/includes/button_for_cart.html
{% load user_filters %}

{% if user.is_authenticated %}
    {% if recipe|recipe_in_cart:user %}
        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
    {% else %}
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
    {% endif %}
{% endif %}

foodgram/templates/includes/button_for_favorite.html
{% load user_filters %}

{% if user.is_authenticated %}
    {% if recipe|in_favorite:user %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    {% else %}
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    {% endif %}
{% endif %}

foodgram/templates/includes/button_for_follow.html
{% load user_filters %}

{% if user != recipe.author %}
    {% if user.is_authenticated %}
        {% if recipe.author|in_follow:user %}
            <li class="single-card__item"><button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span> Отписаться от автора </button></li>
        {% else %}
            <li class="single-card__item"><button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Подписаться на автора</button></li>
        {% endif %}
    {% endif %}
{% endif %}

foodgram/templates/includes/comments.html
{% load user_filters %}
{% load static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
<div class="form-container">
    <div class="form">
        {% for comment in comments %}
            <h5 class="single-card__section-text"><a href="{% url 'profile' comment.author %}" name="comment_{{ item.id }}">{{ comment.author.get_full_name }}</a> - {{ comment.created }}</h5>
            <p class=" single-card__section-text">{{ comment.text }}</p>
        {% endfor %}    
        {% if user.is_authenticated %} 
        <form action="{% url 'social:add_comment' recipe.id %}" method="post">
            {% csrf_token %}
            <div class="form__group">
                <div class="form__field-group-comment">
                    {{ form.text|addclass:"form__textarea" }}
                    {% if form.errors %}
                        {% for error in field.errors %}
                            <span class="form__error">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Отправить комментарий</button>
            </div>
        </form>
        {% endif %}
    </div>
</div>

foodgram/templates/includes/follow_card.html
{% load static %}
{% load user_filters %}
{% csrf_token %}
<div class="card-list">
    {% for follow in page %}
        <div class="card-user" data-author="{{ follow.author_id }}">
            <div class="card-user__header">
                <h2 class="card-user__title"><a href="{% url 'profile' follow.author %}" style="color: black">{{ follow.author.get_full_name }}</a></h2>
            </div>
            {% for recipe in follow.author.recipes.all|slice:":3" %}
                <div class="card-user__body">
                    <ul class="card-user__items">
                        <li class="card-user__item">
                            <div class="recipe">
                                <a href="{% url 'recipe' recipe.id %}" class="link">
                                    <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}"
                                         class="recipe__image"></a>
                                <h3 class="recipe__title">
                                    {{ recipe.title }}</h3>
                                <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мину{{ recipe.cooking_time|rupluralize:"та,ты,т"}}</p>
                            </div>
                        </li>
                    </ul>
                </div>
            {% endfor %}
            <li class="card-user__item">
                {% if follow.author.recipes.all|length >= 3 %}
                    <a href="{% url 'profile' follow.author.username %}" class="card-user__link link">Еще {{ follow.author.recipes.all.count|add:-3 }} рецеп{{ follow.author.recipes.all.count|add:-3|rupluralize:"т,та,тов" }}...</a>
                {% endif %}
            </li>

            <div class="card-user__footer">
                <button class="button button_style_light-blue button_size_auto" name="subscribe"><span class="icon-check button__icon"></span>Отписаться</button>
            </div>
        </div>
    {% endfor %}
</div>

foodgram/templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'about-project' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about-author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about-spec' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

foodgram/templates/includes/head.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
        {% if user.is_authenticated %}
            <ul class="nav__items list">
                <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                <li class="nav__item {% if follow %}nav__item_active{% endif %}"><a href="{% url 'social:follow_index' %}" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item {% if new_recipe %}nav__item_active{% endif %}"><a href="{% url 'recipe_new' %}" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item {% if favorit %}nav__item_active{% endif %}"><a href="{% url 'social:favorit_index' %}" class="nav__link link">Избранное</a></li>{#  {% url 'shopping_list' %} #}
                <li class="nav__item {% if cart_list %}nav__item_active{% endif %}"><a href="{% url 'cart_list' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{ count }}</span></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item {% if password_change %}nav__item_active{% endif %}"><a href="{% url 'index' %}""><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
            </ul>
        {% else %}
            <ul class="nav__items list">
                <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index' %}""><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item {% if login %}nav__item_active{% endif %}"><a href="{% url 'index' %}""><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
        {% endif %}
        </div>
    </nav>
</header>

foodgram/templates/includes/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}{{ pages }}"><span class="icon-left"></span></a></li>
        {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="#" tabindex="-1" aria-disabled="true"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><span class="pagination__link link">{{ i }}</span></span></li>
                {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}{{ pages }}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}
        {% if items.has_next %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}{{ pages }}"><span class="icon-right"></span></a></li>
        {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="#" tabindex="-1" aria-disabled="true"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

foodgram/templates/includes/recipe.html
{% extends 'base.html' %}
{% block title %} {{ recipe.title }} {% endblock %}
{% block head %}
    {% include 'includes/head.html' %}
{% endblock %}
{% load static %}
{% load user_filters %}
{% block content %}
<link rel="stylesheet" href="{% static 'pages/index.css' %}">
<link rel="stylesheet" href="{% static 'pages/single.css' %}">
  {% csrf_token %}
        <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
            <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ recipe.title }}</h1>
                    {% include 'includes/button_for_favorite.html' %}  
                </div>
                <ul class="single-card__items">
                    {% include 'includes/tags_for_card.html' %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мину{{ recipe.cooking_time|rupluralize:"та,ты,т" }}</p>
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span><a style="color: #000" href="{% url 'profile' recipe.author.username %}">{{ recipe.author.get_full_name }}</a></p></li>
                        {% if user == recipe.author %}
                            <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipe_edit' recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                      </ul>
                    </div>
                    <ul class="single-card__items">
                        {% include 'includes/button_for_cart.html' %}
                        {% include 'includes/button_for_follow.html' %}
                    </ul>  
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингридиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for ingr in recipe.quantities.all %}
                            <p class=" single-card__section-item">{{ ingr.ingredient.title }} - {{ ingr.quantity }} {{ ingr.ingredient.dimension }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
                </div>
            </div>
        </div>
        {% include 'includes/comments.html' with comments=comments %}
{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>


<script src="{% static '/js/components/Purchases.js' %}"></script>
<script src="{% static '/js/components/Favorites.js' %}"></script>
<script src="{% static '/js/components/Subscribe.js' %}"></script>


<script src="{% static '/js/components/MainCards.js' %}"></script>
<script src="{% static '/js/components/SingleCard.js' %}"></script>


<script src="{% static '/js/singlePage.js' %}"></script>
{% endblock %}
{% endblock %}

foodgram/templates/includes/recipe_small.html
{% load user_filters %}
{% csrf_token %}
<div class="card" data-id="{{ recipe.id }}">
    <a href="{% url 'recipe' recipe.id %}" class="link"><img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe' recipe.id %}" target="_blank">{{ recipe.title }}</a>
        <ul class="card__items">
        {% include 'includes/tags_for_card.html' %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мину{{ recipe.cooking_time|rupluralize:"та,ты,т" }}</p>
            <p class="card__text"><span class="icon-user"></span> <a href="{% url 'profile' recipe.author.username %}" style="color: black">{{ recipe.author.get_full_name}}</a></p>
            <p class="card__text"><span class="icon-comment"></span> <a href="{% url 'recipe' recipe.id %}" style="color: black">{{ recipe.comments.count }} комментари{{ recipe.comments.count|rupluralize:"й,я,ев" }}</a></p>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <div class="card__footer">
            {% include 'includes/button_for_cart.html' %}
            {% include 'includes/button_for_favorite.html' %}
        </div>
    {% endif %}
</div>

foodgram/templates/includes/tags.html
{% load user_filters %}
<ul class="tags">
  <li class="tags__item">
    <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange {% if 'breakfast' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"breakfast" }}"></a>
    <span class="tags__label">Завтрак</span>
  </li>
  <li class="tags__item">
    <a id="lunch" class="tags__checkbox tags__checkbox_style_green {% if 'lunch' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"lunch" }}"></a>
    <span for="lunch" class="tags__label">Обед</span>
  </li>
  <li class="tags__item">
    <a id="dinner" class="tags__checkbox tags__checkbox_style_purple {% if 'dinner' in tags %}tags__checkbox_active{% endif %}" href="{{ request.path }}?tags={{ request|formatting_tags:"dinner" }}"></a>
    <label for="dinner" class="tags__label">Ужин</label>
  </li>
</ul>

foodgram/templates/includes/tags_for_card.html
{% for tag in recipe.tag.all %}
    {% if tag.title == 'lunch' %}
        <li class="single-card__item"><span class="badge badge_style_green">Обед</span></li>
    {% elif tag.title == 'breakfast' %}
        <li class="single-card__item"><span class="badge badge_style_orange">Завтрак</span></li>
    {% else %}
        <li class="single-card__item"><span class="badge badge_style_purple">Ужин</span></li>
    {% endif %}
{% endfor %}